---
 hspawn-point:
    x: ""
    y: ""
    z: ""
 sspawn-point:
    x: ""
    y: ""
    z: ""
 lspawn-point:
    x: ""
    y: ""
    z: ""
    
 #Use an ยง here for the colors of the text
 #Formatting Codes : https://minecraft.gamepedia.com/Formatting_codes
 theme: "ยง"
...
  
