name: SpawnsCore
main: Trxgically\SpawnsCore\Main
api: 3.0.0
version: 0.1
author: Trxgically
commands:
 sc:
  description: "SpawnsCore default command"
 hub:
  description: "Teleport to the hub spawnpoint"
 spawn:
  description: "Teleport to the spawn spawnpoint"
 lobby:
  description: "Teleport to the lobby spawnpoint"
